"""DXCC实体工具 - 通过呼号前缀推断DXCC实体名称"""

import re
from typing import Optional

# 常见业余无线电 DXCC 前缀映射（核心列表）
# 格式: (前缀正则, 实体名称)
DXCC_PREFIXES = [
    (r"^BV", "Taiwan"),
    (r"^BY", "China"),
    (r"^B[0-9]", "China"),
    (r"^BA[0-9]", "China"),
    (r"^BD[0-9]", "China"),
    (r"^BG[0-9]", "China"),
    (r"^BH[0-9]", "China"),
    (r"^BI[0-9]", "China"),
    (r"^BJ[0-9]", "China"),
    (r"^BM", "Taiwan"),
    (r"^BN", "Taiwan"),
    (r"^BO", "Taiwan"),
    (r"^BU", "Taiwan"),
    (r"^BW", "Taiwan"),
    (r"^BX", "Taiwan"),
    (r"^C", "Chile"),
    (r"^CE", "Chile"),
    (r"^CM", "Cuba"),
    (r"^CO", "Cuba"),
    (r"^CP", "Bolivia"),
    (r"^CT", "Portugal"),
    (r"^CU", "Azores"),
    (r"^CX", "Uruguay"),
    (r"^D", "Germany"),
    (r"^DA", "Germany"),
    (r"^DF", "Germany"),
    (r"^DG", "Germany"),
    (r"^DH", "Germany"),
    (r"^DJ", "Germany"),
    (r"^DK", "Germany"),
    (r"^DL", "Germany"),
    (r"^DM", "Germany"),
    (r"^E", "Spain"),
    (r"^EA", "Spain"),
    (r"^EA6", "Balearic Islands"),
    (r"^EA8", "Canary Islands"),
    (r"^EI", "Ireland"),
    (r"^EJ", "Ireland"),
    (r"^EK", "Armenia"),
    (r"^EL", "Liberia"),
    (r"^ER", "Moldova"),
    (r"^ES", "Estonia"),
    (r"^ET", "Ethiopia"),
    (r"^EU", "Belarus"),
    (r"^EV", "Belarus"),
    (r"^EW", "Belarus"),
    (r"^EX", "Kyrgyzstan"),
    (r"^EY", "Tajikistan"),
    (r"^EZ", "Turkmenistan"),
    (r"^F", "France"),
    (r"^G", "England"),
    (r"^GD", "Isle of Man"),
    (r"^GI", "Northern Ireland"),
    (r"^GJ", "Jersey"),
    (r"^GM", "Scotland"),
    (r"^GU", "Guernsey"),
    (r"^GW", "Wales"),
    (r"^H", "Hungary"),
    (r"^HA", "Hungary"),
    (r"^HB", "Switzerland"),
    (r"^HB0", "Liechtenstein"),
    (r"^HC", "Ecuador"),
    (r"^HD", "Ecuador"),
    (r"^HI", "Dominican Republic"),
    (r"^HK", "Colombia"),
    (r"^HL", "South Korea"),
    (r"^HM", "North Korea"),
    (r"^HP", "Panama"),
    (r"^HR", "Honduras"),
    (r"^HS", "Thailand"),
    (r"^HV", "Vatican"),
    (r"^HZ", "Saudi Arabia"),
    (r"^I", "Italy"),
    (r"^IS", "Sardinia"),
    (r"^J", "Japan"),
    (r"^JA", "Japan"),
    (r"^JE", "Japan"),
    (r"^JF", "Japan"),
    (r"^JG", "Japan"),
    (r"^JH", "Japan"),
    (r"^JI", "Japan"),
    (r"^JJ", "Japan"),
    (r"^JK", "Japan"),
    (r"^JL", "Japan"),
    (r"^JM", "Japan"),
    (r"^JN", "Japan"),
    (r"^JO", "Japan"),
    (r"^JP", "Japan"),
    (r"^JQ", "Japan"),
    (r"^JR", "Japan"),
    (r"^JS", "South Korea (disputed)"),
    (r"^K", "United States"),
    (r"^KG4", "Guantanamo Bay"),
    (r"^KH0", "Mariana Islands"),
    (r"^KH1", "Baker & Howland Islands"),
    (r"^KH2", "Guam"),
    (r"^KH3", "Johnston Island"),
    (r"^KH4", "Midway Island"),
    (r"^KH5", "Palmyra & Jarvis Islands"),
    (r"^KH6", "Hawaii"),
    (r"^KH7", "Kure Island"),
    (r"^KH8", "American Samoa"),
    (r"^KH9", "Wake Island"),
    (r"^KL", "Alaska"),
    (r"^KP1", "Navassa Island"),
    (r"^KP2", "Virgin Islands"),
    (r"^KP3", "Virgin Islands"),
    (r"^KP4", "Puerto Rico"),
    (r"^KP5", "Desecheo Island"),
    (r"^LA", "Norway"),
    (r"^LB", "Norway"),
    (r"^LC", "Norway"),
    (r"^LU", "Argentina"),
    (r"^LX", "Luxembourg"),
    (r"^LY", "Lithuania"),
    (r"^LZ", "Bulgaria"),
    (r"^N", "United States"),
    (r"^OD", "Lebanon"),
    (r"^OE", "Austria"),
    (r"^OH", "Finland"),
    (r"^OH0", "Aland Islands"),
    (r"^OJ0", "Market Reef"),
    (r"^OK", "Czech Republic"),
    (r"^OL", "Czech Republic"),
    (r"^OM", "Slovakia"),
    (r"^ON", "Belgium"),
    (r"^OT", "Belgium"),
    (r"^OZ", "Denmark"),
    (r"^P", "USA (Pacific trust)"),
    (r"^PA", "Netherlands"),
    (r"^PD", "Netherlands"),
    (r"^PE", "Netherlands"),
    (r"^PG", "Netherlands"),
    (r"^PI", "Netherlands"),
    (r"^PJ2", "Curacao"),
    (r"^PJ4", "Bonaire"),
    (r"^PJ7", "Sint Maarten"),
    (r"^PP", "Brazil"),
    (r"^PQ", "Brazil"),
    (r"^PR", "Brazil"),
    (r"^PS", "Brazil"),
    (r"^PT", "Brazil"),
    (r"^PU", "Brazil"),
    (r"^PV", "Brazil"),
    (r"^PW", "Brazil"),
    (r"^PX", "Brazil"),
    (r"^PY", "Brazil"),
    (r"^R", "European Russia"),
    (r"^RA", "European Russia"),
    (r"^RK", "European Russia"),
    (r"^RN", "European Russia"),
    (r"^RU", "European Russia"),
    (r"^RV", "European Russia"),
    (r"^RW", "European Russia"),
    (r"^RX", "European Russia"),
    (r"^UA", "European Russia"),
    (r"^UA0", "Asiatic Russia"),
    (r"^UA1", "European Russia"),
    (r"^UA2", "Kaliningrad"),
    (r"^UA9", "Asiatic Russia"),
    (r"^UB", "European Russia"),
    (r"^UC", "European Russia"),
    (r"^UD", "European Russia"),
    (r"^UE", "European Russia"),
    (r"^UF", "European Russia"),
    (r"^UG", "European Russia"),
    (r"^UH", "European Russia"),
    (r"^UI", "European Russia"),
    (r"^UJ", "European Russia"),
    (r"^UK", "Uzbekistan"),
    (r"^UL", "Kazakhstan"),
    (r"^UM", "European Russia"),
    (r"^UN", "Kazakhstan"),
    (r"^UO", "European Russia"),
    (r"^UP", "Kazakhstan"),
    (r"^UQ", "European Russia"),
    (r"^UR", "Ukraine"),
    (r"^US", "Ukraine"),
    (r"^UT", "Ukraine"),
    (r"^UU", "Ukraine"),
    (r"^UW", "Ukraine"),
    (r"^UY", "Ukraine"),
    (r"^UZ", "Ukraine"),
    (r"^V2", "Antigua & Barbuda"),
    (r"^V3", "Belize"),
    (r"^V4", "St. Kitts & Nevis"),
    (r"^V5", "Namibia"),
    (r"^V6", "Micronesia"),
    (r"^V7", "Marshall Islands"),
    (r"^V8", "Brunei"),
    (r"^VE", "Canada"),
    (r"^VF", "Canada"),
    (r"^VG", "Canada"),
    (r"^VO", "Canada (Newfoundland)"),
    (r"^VY", "Canada"),
    (r"^VK", "Australia"),
    (r"^VK0", "Macquarie Island"),
    (r"^VK1", "Australia"),
    (r"^VK2", "Australia"),
    (r"^VK3", "Australia"),
    (r"^VK9L", "Lord Howe Island"),
    (r"^VK9M", "Mellish Reef"),
    (r"^VK9N", "Norfolk Island"),
    (r"^VK9W", "Willis Island"),
    (r"^VK9X", "Christmas Island"),
    (r"^VK9Y", "Cocos-Keeling Islands"),
    (r"^VP2E", "Anguilla"),
    (r"^VP2M", "Montserrat"),
    (r"^VP2V", "British Virgin Islands"),
    (r"^VP5", "Turks & Caicos Islands"),
    (r"^VP6", "Pitcairn Island"),
    (r"^VP8", "Falkland Islands"),
    (r"^VP9", "Bermuda"),
    (r"^VQ9", "Chagos Islands"),
    (r"^VR", "Hong Kong"),
    (r"^VS", "United Kingdom (not used)"),
    (r"^VU", "India"),
    (r"^W", "United States"),
    (r"^X", "Mexico"),
    (r"^XA", "Mexico"),
    (r"^XB", "Mexico"),
    (r"^XC", "Mexico"),
    (r"^XD", "Mexico"),
    (r"^XE", "Mexico"),
    (r"^XF", "Mexico"),
    (r"^XG", "Mexico"),
    (r"^XH", "Mexico"),
    (r"^XI", "Mexico"),
    (r"^XJ", "Canada"),
    (r"^XL", "Canada"),
    (r"^XM", "Canada"),
    (r"^XP", "Greenland"),
    (r"^XT", "Burkina Faso"),
    (r"^XU", "Cambodia"),
    (r"^XW", "Laos"),
    (r"^XX", "Portugal (not used)"),
    (r"^XY", "Myanmar"),
    (r"^XZ", "Myanmar"),
    (r"^Y", "Canada"),
    (r"^Y2", "Germany (not used)"),
    (r"^YJ", "Vanuatu"),
    (r"^YK", "Syria"),
    (r"^YL", "Latvia"),
    (r"^YM", "Turkey"),
    (r"^YN", "Nicaragua"),
    (r"^YO", "Romania"),
    (r"^YP", "Romania"),
    (r"^YQ", "Romania"),
    (r"^YR", "Romania"),
    (r"^YS", "El Salvador"),
    (r"^YT", "Serbia"),
    (r"^YU", "Serbia"),
    (r"^YV", "Venezuela"),
    (r"^YW", "Venezuela"),
    (r"^YV0", "Aves Island"),
    (r"^Z", "Canada (not used)"),
    (r"^Z2", "Zimbabwe"),
    (r"^Z3", "North Macedonia"),
    (r"^ZA", "Albania"),
    (r"^ZB", "United Kingdom (not used)"),
    (r"^ZC4", "UK Sovereign Bases (Cyprus)"),
    (r"^ZD7", "St. Helena"),
    (r"^ZD8", "Ascension Island"),
    (r"^ZD9", "Tristan da Cunha"),
    (r"^ZF", "Cayman Islands"),
    (r"^ZK2", "Niue"),
    (r"^ZK3", "Tokelau Islands"),
    (r"^ZL", "New Zealand"),
    (r"^ZM", "New Zealand"),
    (r"^ZN", "New Zealand"),
    (r"^ZO", "New Zealand"),
    (r"^ZP", "Paraguay"),
    (r"^ZS", "South Africa"),
    (r"^ZT", "South Africa"),
    (r"^ZU", "South Africa"),
    (r"^ZV", "Brazil"),
    (r"^ZX", "Brazil"),
    (r"^ZZ", "Brazil"),
    (r"^3A", "Monaco"),
    (r"^3B6", "Mauritius (Agalega)"),
    (r"^3B7", "Mauritius (St. Brandon)"),
    (r"^3B8", "Mauritius"),
    (r"^3B9", "Rodriguez Island"),
    (r"^3C", "Equatorial Guinea"),
    (r"^3DA", "Swaziland"),
    (r"^3V", "Tunisia"),
    (r"^3W", "Vietnam"),
    (r"^3X", "Guinea"),
    (r"^3Y", "Norway (not used)"),
    (r"^4A", "Mexico"),
    (r"^4B", "Mexico"),
    (r"^4C", "Mexico"),
    (r"^4D", "Philippines"),
    (r"^4E", "Philippines"),
    (r"^4F", "Philippines"),
    (r"^4G", "Philippines"),
    (r"^4H", "Philippines"),
    (r"^4I", "Philippines"),
    (r"^4J", "Azerbaijan"),
    (r"^4L", "Georgia"),
    (r"^4O", "Montenegro"),
    (r"^4P", "Sri Lanka"),
    (r"^4R", "Sri Lanka"),
    (r"^4S", "Sri Lanka"),
    (r"^4U", "United Nations (ITU)"),
    (r"^4W", "Timor-Leste"),
    (r"^4X", "Israel"),
    (r"^4Z", "Israel"),
    (r"^5A", "Libya"),
    (r"^5B", "Cyprus"),
    (r"^5H", "Tanzania"),
    (r"^5I", "Tanzania"),
    (r"^5N", "Nigeria"),
    (r"^5O", "Nigeria"),
    (r"^5R", "Madagascar"),
    (r"^5T", "Mauritania"),
    (r"^5U", "Niger"),
    (r"^5V", "Togo"),
    (r"^5W", "Samoa"),
    (r"^5X", "Uganda"),
    (r"^5Y", "Kenya"),
    (r"^5Z", "Kenya"),
    (r"^6A", "Egypt"),
    (r"^6C", "Syria"),
    (r"^6E", "Mexico"),
    (r"^6F", "Mexico"),
    (r"^6G", "Mexico"),
    (r"^6H", "Mexico"),
    (r"^6I", "Mexico"),
    (r"^6J", "Mexico"),
    (r"^6K", "South Korea"),
    (r"^6L", "South Korea"),
    (r"^6M", "South Korea"),
    (r"^6N", "South Korea"),
    (r"^6O", "Somalia"),
    (r"^6V", "Senegal"),
    (r"^6W", "Senegal"),
    (r"^6Y", "Jamaica"),
    (r"^7O", "Yemen"),
    (r"^7P", "Lesotho"),
    (r"^7Q", "Malawi"),
    (r"^7S", "Sweden"),
    (r"^7T", "Algeria"),
    (r"^7X", "Algeria"),
    (r"^7Z", "Algeria"),
    (r"^8A", "Indonesia"),
    (r"^8B", "Indonesia"),
    (r"^8C", "Indonesia"),
    (r"^8D", "Indonesia"),
    (r"^8E", "Indonesia"),
    (r"^8F", "Indonesia"),
    (r"^8G", "Indonesia"),
    (r"^8H", "Indonesia"),
    (r"^8I", "Indonesia"),
    (r"^8J", "Japan"),
    (r"^8N", "Japan"),
    (r"^8P", "Barbados"),
    (r"^8Q", "Maldives"),
    (r"^8R", "Guyana"),
    (r"^9A", "Croatia"),
    (r"^9G", "Ghana"),
    (r"^9H", "Malta"),
    (r"^9I", "Zambia"),
    (r"^9J", "Zambia"),
    (r"^9K", "Kuwait"),
    (r"^9L", "Sierra Leone"),
    (r"^9M2", "West Malaysia"),
    (r"^9M6", "East Malaysia"),
    (r"^9M8", "Brunei"),
    (r"^9N", "Nepal"),
    (r"^9O", "Democratic Republic of the Congo"),
    (r"^9Q", "Democratic Republic of the Congo"),
    (r"^9R", "Democratic Republic of the Congo"),
    (r"^9T", "Democratic Republic of the Congo"),
    (r"^9U", "Burundi"),
    (r"^9V", "Singapore"),
    (r"^9W", "West Malaysia"),
    (r"^9X", "Rwanda"),
    (r"^9Y", "Trinidad & Tobago"),
    (r"^9Z", "Trinidad & Tobago"),
    (r"^A[2-9]", "USA (not used, but catch)"),
    (r"^A4", "Oman"),
    (r"^A6", "United Arab Emirates"),
    (r"^A7", "Qatar"),
    (r"^A9", "Bahrain"),
    (r"^S0", "Western Sahara"),
    (r"^S2", "Bangladesh"),
    (r"^S3", "Bangladesh"),
    (r"^S5", "Slovenia"),
    (r"^S7", "Seychelles"),
    (r"^S9", "Sao Tome & Principe"),
    (r"^S21", "Bangladesh"),
    (r"^S79", "Seychelles"),
    (r"^T2", "Tuvalu"),
    (r"^T3[0-9]", "Kiribati"),
    (r"^T30", "West Kiribati"),
    (r"^T31", "Central Kiribati"),
    (r"^T32", "East Kiribati"),
    (r"^T33", "Banaba Island"),
    (r"^T5", "Somalia"),
    (r"^T7", "San Marino"),
    (r"^T8", "Palau"),
    (r"^TA", "Turkey"),
    (r"^TC", "Turkey"),
    (r"^TF", "Iceland"),
    (r"^TG", "Guatemala"),
    (r"^TI", "Costa Rica"),
    (r"^TJ", "Cameroon"),
    (r"^TK", "Corsica"),
    (r"^TL", "Central African Republic"),
    (r"^TM", "France"),
    (r"^TN", "Republic of the Congo"),
    (r"^TO", "France (overseas)"),
    (r"^TP", "France (overseas)"),
    (r"^TQ", "France (overseas)"),
    (r"^TR", "Gabon"),
    (r"^TS", "Tunisia"),
    (r"^TT", "Chad"),
    (r"^TU", "Ivory Coast"),
    (r"^TV", "Ivory Coast"),
    (r"^TW", "Ivory Coast"),
    (r"^TX", "France (overseas)"),
    (r"^TY", "Benin"),
    (r"^TZ", "Mali"),
    (r"^U[^SAR0-9]", "Ukraine (catch)"),
    (r"^S1", "Bangladesh (not used)"),
    (r"^S6", "Singapore (not used)"),
    (r"^S8", "South Africa (not used)"),
    (r"^S4", "Bangladesh (not used)"),
]


def lookup_dxcc(call_sign: str) -> Optional[str]:
    """通过呼号前缀推断DXCC实体名称"""
    if not call_sign:
        return None
    cs = call_sign.strip().upper()

    # 先匹配斜杠后的叠加前缀：B7/BA7ABC → 用 BA7ABC 匹配
    # 但常见斜杠格式如 B7/BA7ABC 表示操作地在 B7 区域，台站呼号为 BA7ABC
    # 取下呼号本体
    if "/" in cs:
        parts = cs.split("/")
        # 取最长的、不含数字开头的部分，通常是台站真实呼号
        candidates = [p for p in parts if not re.match(r'^[0-9A-Z]{1,3}$', p)]
        if candidates:
            cs = max(candidates, key=len)

    # 按前缀匹配（从长到短）
    for pattern, entity in DXCC_PREFIXES:
        if re.match(pattern, cs):
            return entity

    return "Unknown"
