"""DXCC实体工具 - 基于ARRL DXCC列表通过呼号前缀推断DXCC实体名称"""

import re
from typing import Optional

# ARRL DXCC前缀映射
# 匹配规则：先按前缀正则的精确度从高到低匹配，将斜杠后的操作地前缀作为主匹配
DXCC_PREFIXES = [
    (r"^1A", "Sov. Mil. Order of Malta"),
    (r"^3A", "Monaco"),
    (r"^3B6", "Agalega & St. Brandon Is."),
    (r"^3B7", "Agalega & St. Brandon Is."),
    (r"^3B8", "Mauritius"),
    (r"^3B9", "Rodrigues I."),
    (r"^3C0", "Annobon I."),
    (r"^3C", "Equatorial Guinea"),
    (r"^3D2R", "Rotuma I."),
    (r"^3D2C", "Conway Reef"),
    (r"^3D2", "Fiji"),
    (r"^3DA", "Kingdom of Eswatini"),
    (r"^3V", "Tunisia"),
    (r"^3W", "Viet Nam"),
    (r"^3X", "Guinea"),
    # 修正：3Y0J, 3Y0Z, 3Y1B 等所有历史与现代布维岛远征，剩下的 3Y 归彼得一世岛
    (r"^3Y[0-9]?[0-9]?[ZJBPZjb]", "Bouvet"),
    (r"^3Y", "Peter 1 I."),
    (r"^4J", "Azerbaijan"),
    (r"^4K", "Azerbaijan"),
    (r"^4L", "Georgia"),
    (r"^4O", "Montenegro"),
    (r"^4S", "Sri Lanka"),
    (r"^4U_ITU", "ITU HQ"),
    (r"^4U_UN", "United Nations HQ"),
    (r"^4W", "Timor - Leste"),
    (r"^4X", "Israel"),
    (r"^4Z", "Israel"),
    (r"^5A", "Libya"),
    (r"^5B", "Cyprus"),
    (r"^5H", "Tanzania"),
    (r"^5I", "Tanzania"),
    (r"^5N", "Nigeria"),
    (r"^5O", "Nigeria"),
    (r"^5R", "Madagascar"),
    (r"^5T", "Mauritania"),
    (r"^5U", "Niger"),
    (r"^5V", "Togo"),
    (r"^5W", "Samoa"),
    (r"^5X", "Uganda"),
    (r"^5Y", "Kenya"),
    (r"^5Z", "Kenya"),
    (r"^6V", "Senegal"),
    (r"^6W", "Senegal"),
    (r"^6Y", "Jamaica"),
    (r"^7O", "Yemen"),
    (r"^7P", "Lesotho"),
    (r"^7Q", "Malawi"),
    (r"^7S", "Sweden"),
    (r"^7T", "Algeria"),
    (r"^7X", "Algeria"),
    (r"^8P", "Barbados"),
    (r"^8Q", "Maldives"),
    (r"^8R", "Guyana"),
    (r"^9A", "Croatia"),
    (r"^9G", "Ghana"),
    (r"^9H", "Malta"),
    (r"^9I", "Zambia"),
    (r"^9J", "Zambia"),
    (r"^9K", "Kuwait"),
    (r"^9L", "Sierra Leone"),
    (r"^9M2", "West Malaysia"),
    (r"^9M6", "East Malaysia"),
    (r"^9M8", "East Malaysia"),
    (r"^9N", "Nepal"),
    (r"^9Q", "Dem. Rep. of Congo"),
    (r"^9R", "Dem. Rep. of Congo"),
    (r"^9T", "Dem. Rep. of Congo"),
    (r"^9U", "Burundi"),
    (r"^9V", "Singapore"),
    (r"^9W", "West Malaysia"),
    (r"^9X", "Rwanda"),
    (r"^9Y", "Trinidad & Tobago"),
    (r"^9Z", "Trinidad & Tobago"),
    (r"^A2", "Botswana"),
    (r"^A3", "Tonga"),
    (r"^A4", "Oman"),
    (r"^A5", "Bhutan"),
    (r"^A6", "United Arab Emirates"),
    (r"^A7", "Qatar"),
    (r"^A9", "Bahrain"),
    (r"^AP", "Pakistan"),
    # === 台湾及附属离岛 (Taiwan & Islands) ===
    (r"^B[VMN]9P", "Pratas I."),                       # 东沙群岛 (优先最高)
    (r"^BV9S", "Spratly Is. (Taiping I.)"),            # 南沙太平岛
    (r"^BO0", "Kinmen & Matsu"),                       # 金门马祖离岛
    (r"^B[VNMUBOPX]", "Taiwan"),                       # 台湾本岛保底匹配 (涵盖 BV, BU, BM, BN, BO, BP, BX)
    # === 中国本岛及其他特殊前缀 ===
    (r"^BS7", "Scarborough Reef"),                     # 黄岩岛
    (r"^B[0-9]", "China"),
    (r"^BA[0-9]", "China"),
    (r"^BD[0-9]", "China"),
    (r"^BG[0-9]", "China"),
    (r"^BH[0-9]", "China"),
    (r"^BI[0-9]", "China"),
    (r"^BJ[0-9]", "China"),
    (r"^BY", "China"),  
    (r"^C2", "Nauru"),
    (r"^C3", "Andorra"),
    (r"^C5", "The Gambia"),
    (r"^C6", "Bahamas"),
    (r"^C8", "Mozambique"),
    (r"^C9", "Mozambique"),
    (r"^CE0[A-Z]", "Easter I."),
    (r"^CE0", "Easter I."),
    (r"^CE9", "Antarctica"),
    (r"^CE", "Chile"),
    (r"^CM", "Cuba"),
    (r"^CN", "Morocco"),
    (r"^CO", "Cuba"),
    (r"^CP", "Bolivia"),
    (r"^CT3", "Madeira Is."),
    (r"^CT", "Portugal"),
    (r"^CU", "Azores"),
    (r"^CV", "Uruguay"),
    (r"^CX", "Uruguay"),
    (r"^CY0", "Sable I."),
    (r"^CY9", "St. Paul I."),
    (r"^D2", "Angola"),
    (r"^D3", "Angola"),
    (r"^D4", "Cape Verde"),
    (r"^D6", "Comoros"),
    (r"^D[A-O]", "Germany"),
    (r"^DP", "Germany (Antarctica/Special)"),
    (r"^DR", "Germany"),
    (r"^DU", "Philippines"),
    (r"^DV", "Philippines"),
    (r"^DW", "Philippines"),
    (r"^DX", "Philippines"),
    (r"^DY", "Philippines"),
    (r"^DZ", "Philippines"),
    (r"^E2", "Thailand"),
    (r"^E3", "Eritrea"),
    (r"^E4", "Palestine"),
    (r"^E5[NSEW]", "S. Cook Is."),
    (r"^E5", "N. Cook Is."),
    (r"^E6", "Niue"),
    (r"^E7", "Bosnia-Herzegovina"),
    (r"^EA6", "Balearic Is."),
    (r"^EA8", "Canary Is."),
    (r"^EA9", "Ceuta & Melilla"),
    (r"^EA", "Spain"),
    (r"^EH6", "Balearic Is."),
    (r"^EH8", "Canary Is."),
    (r"^EH9", "Ceuta & Melilla"),
    (r"^EH", "Spain"),
    (r"^EI", "Ireland"),
    (r"^EJ", "Ireland"),
    (r"^EK", "Armenia"),
    (r"^EL", "Liberia"),
    (r"^EP", "Iran"),
    (r"^EQ", "Iran"),
    (r"^ER", "Moldova"),
    (r"^ES", "Estonia"),
    (r"^ET", "Ethiopia"),
    (r"^EU", "Belarus"),
    (r"^EV", "Belarus"),
    (r"^EW", "Belarus"),
    (r"^EX", "Kyrgyzstan"),
    (r"^EY", "Tajikistan"),
    (r"^EZ", "Turkmenistan"),
    (r"^F[GJKLMPSTWY]", "France (overseas)"),
    (r"^F", "France"),
    (r"^GX", "England"),
    (r"^G[DMPSUWK]?", "United Kingdom"),
    (r"^H4[02]", "Temotu Province"),
    (r"^H4", "Solomon Is."),
    (r"^HA", "Hungary"),
    (r"^HB0", "Liechtenstein"),
    (r"^HB", "Switzerland"),
    (r"^HC8", "Galapagos Is."),
    (r"^HC", "Ecuador"),
    (r"^HD8", "Galapagos Is."),
    (r"^HD", "Ecuador"),
    (r"^HF", "Poland"),
    (r"^HG", "Hungary"),
    (r"^HH", "Haiti"),
    (r"^HI", "Dominican Republic"),
    (r"^HJ", "Colombia"),
    (r"^HK0[MAS]", "San Andres & Providencia"),
    (r"^HK0", "Malpelo I."),
    (r"^HK", "Colombia"),
    (r"^HL", "Republic of Korea"),
    (r"^HM", "Dem. People's Rep. of Korea"),
    (r"^HO", "Panama"),
    (r"^HP", "Panama"),
    (r"^HQ", "Honduras"),
    (r"^HR", "Honduras"),
    (r"^HS", "Thailand"),
    (r"^HT", "Nicaragua"),
    (r"^HV", "Vatican"),
    (r"^HZ", "Saudi Arabia"),
    (r"^I[SM]", "Sardinia"),
    (r"^I", "Italy"),
    (r"^J2", "Djibouti"),
    (r"^J3", "Grenada"),
    (r"^J5", "Guinea-Bissau"),
    (r"^J6", "St. Lucia"),
    (r"^J7", "Dominica"),
    (r"^J8", "St. Vincent"),
    # 修正：剥离离岛后，合并日本 JA-JS 规则，彻底解决 JS1AAA 等本土电台被误判为韩国争议区的问题
    (r"^JD1M", "Minami Torishima"),
    (r"^JD1O", "Ogasawara"),
    (r"^J[A-S]", "Japan"),
    (r"^JT", "Mongolia"),
    (r"^JV", "Mongolia"),
    (r"^JW", "Svalbard"),
    (r"^JX", "Jan Mayen"),
    (r"^JY", "Jordan"),
    # === 美属太平洋离岛短呼号防误判修正区（必须写在本土 K/N/W 之前） ===
    # 具体前缀必须在通配 [KNW]H[0-9] 之前，否则 KH8 会被误判为 Hawaii
    (r"^KG4", "Guantanamo Bay"),
    (r"^KH0", "Mariana Is."),
    (r"^KH1", "Baker & Howland Is."),
    (r"^KH2", "Guam"),
    (r"^KH3", "Johnston I."),
    (r"^KH4", "Midway I."),
    (r"^KH5K", "Kure I."),
    (r"^KH5", "Palmyra & Jarvis Is."),
    (r"^KH6", "Hawaii"),
    (r"^KH7K", "Kure I."),
    (r"^KH7", "Hawaii"),
    (r"^KH8", "American Samoa"),
    (r"^KH9", "Wake I."),
    (r"^[KNW]H[0-9]", "Hawaii/Pacific US Ter."),       # 通配兜底（KH6/WH6 等已被上面具体规则捕获）
    (r"^KL", "Alaska"),
    (r"^KP1", "Navassa I."),
    (r"^KP2", "Virgin Is."),
    (r"^KP3", "Puerto Rico"),
    (r"^KP4", "Puerto Rico"),
    (r"^KP5", "Desecheo I."),
    # 美国本土
    (r"^K", "United States"),
    (r"^N", "United States"),
    (r"^W", "United States"),
    (r"^LA", "Norway"),
    (r"^LB", "Norway"),
    (r"^LC", "Norway"),
    (r"^LD", "Norway"),
    (r"^LE", "Norway"),
    (r"^LF", "Norway"),
    (r"^LG", "Norway"),
    (r"^LH", "Norway"),
    (r"^LI", "Norway"),
    (r"^LJ", "Norway"),
    (r"^LK", "Norway"),
    (r"^LL", "Norway"),
    (r"^LM", "Norway"),
    (r"^LN", "Norway"),
    (r"^LU", "Argentina"),
    (r"^LV", "Argentina"),
    (r"^LW", "Argentina"),
    (r"^LX", "Luxembourg"),
    (r"^LY", "Lithuania"),
    (r"^LZ", "Bulgaria"),
    (r"^M", "United Kingdom"),
    (r"^OA", "Peru"),
    (r"^OB", "Peru"),
    (r"^OC", "Peru"),
    (r"^OD", "Lebanon"),
    (r"^OE", "Austria"),
    (r"^OF", "Finland"),
    (r"^OG", "Finland"),
    (r"^OH0", "Aland Is."),
    (r"^OH", "Finland"),
    (r"^OI", "Finland"),
    (r"^OJ0", "Market Reef"),
    (r"^OK", "Czech Republic"),
    (r"^OL", "Czech Republic"),
    (r"^OM", "Slovak Republic"),
    (r"^ON", "Belgium"),
    (r"^OP", "Belgium"),
    (r"^OQ", "Belgium"),
    (r"^OR", "Belgium"),
    (r"^OS", "Belgium"),
    (r"^OT", "Belgium"),
    (r"^OU", "Denmark"),
    (r"^OV", "Denmark"),
    (r"^OW", "Denmark"),
    (r"^OX", "Greenland"),
    (r"^OY", "Faroe Is."),
    (r"^OZ", "Denmark"),
    (r"^P2", "Papua New Guinea"),
    (r"^P4", "Aruba"),
    # 修正：扩充朝鲜 ITU 分配前缀至 P5-P9 完整全集
    (r"^P[5-9]", "Dem. People's Rep. of Korea"),
    (r"^PA", "Netherlands"),
    (r"^PB", "Netherlands"),
    (r"^PC", "Netherlands"),
    (r"^PD", "Netherlands"),
    (r"^PE", "Netherlands"),
    (r"^PF", "Netherlands"),
    (r"^PG", "Netherlands"),
    (r"^PH", "Netherlands"),
    (r"^PI", "Netherlands"),
    (r"^PJ2", "Curacao"),
    (r"^PJ4", "Bonaire"),
    (r"^PJ5", "Saba & St. Eustatius"),
    (r"^PJ6", "Saba & St. Eustatius"),
    (r"^PJ7", "Sint Maarten"),
    (r"^PP", "Brazil"),
    (r"^PQ", "Brazil"),
    (r"^PR", "Brazil"),
    (r"^PS", "Brazil"),
    (r"^PT", "Brazil"),
    (r"^PU", "Brazil"),
    (r"^PV", "Brazil"),
    (r"^PW", "Brazil"),
    (r"^PX", "Brazil"),
    (r"^PY", "Brazil"),
    (r"^PZ", "Suriname"),
    # 1. 俄罗斯特殊极地岛屿/飞地（Special Islands/Exclaves）
    (r"^R1FJ", "Franz Josef Land"),                    # 法兰士约瑟夫地旧前缀
    (r"^R1F", "Franz Josef Land"),                     # 法兰士约瑟夫地
    (r"^RA2F", "Kaliningrad"),                         # 加里宁格勒飞地 (RA2)
    (r"^R2F", "Kaliningrad"),                          # 加里宁格勒飞地短呼号 (R2)
    # 2. 俄罗斯亚洲部分 (Asiatic Russia)
    (r"^R0", "Asiatic Russia"),                         # 纯 0 数字短呼号 (如 R0AAA)
    (r"^R[A-Z]0", "Asiatic Russia"),                    # 字母+0 复合前缀 (如 RC0AAA)
    (r"^R[89][FGXfgx]", "European Russia"),            # 特例：8/9 后面紧跟 FGX 的属于欧洲
    (r"^R[89]", "Asiatic Russia"),                      # 剩下的 8/9 短呼号归亚洲 (如 R9HQ)
    (r"^R[A-Z][89][FGXfgx]", "European Russia"),        # 特例：双字母前缀+8/9 且后缀首字为 FGX 的归欧洲
    (r"^R[A-Z][89]", "Asiatic Russia"),                 # 双字母前缀+8/9 的其余全部归亚洲 (如 RA9A, RC8W)
    # 3. 俄罗斯欧洲部分 (European Russia)
    (r"^R[1-7]", "European Russia"),                    # 纯数字 1-7 短呼号 (如 R1AAA 完美匹配)
    (r"^R[A-Z][1-7]", "European Russia"),               # 标准双字母前缀 1-7 开头 (如 RC3A)
    (r"^RA", "European Russia"),                        # 保底基础前缀
    (r"^R[A-Z]", "European Russia"),                    
    (r"^S0", "Western Sahara"),
    (r"^S2", "Bangladesh"),
    (r"^S3", "Bangladesh"),
    (r"^S5", "Slovenia"),
    (r"^S7", "Seychelles"),
    (r"^S9", "Sao Tome & Principe"),
    (r"^SA", "Sweden"),
    (r"^SB", "Sweden"),
    (r"^SC", "Sweden"),
    (r"^SD", "Sweden"),
    (r"^SE", "Sweden"),
    (r"^SF", "Sweden"),
    (r"^SG", "Sweden"),
    (r"^SH", "Sweden"),
    (r"^SI", "Sweden"),
    (r"^SJ", "Sweden"),
    (r"^SK", "Sweden"),
    (r"^SL", "Sweden"),
    (r"^SM", "Sweden"),
    (r"^SN", "Poland"),
    (r"^SO", "Poland"),
    (r"^SP", "Poland"),
    (r"^SQ", "Poland"),
    (r"^SR", "Poland"),
    (r"^ST", "Sudan"),
    (r"^SU", "Egypt"),
    (r"^SV[A5]", "Mount Athos"),
    (r"^SV5", "Dodecanese"),
    (r"^SV9", "Crete"),
    (r"^SV", "Greece"),
    (r"^SZ", "Greece"),
    (r"^T2", "Tuvalu"),
    (r"^T30", "West Kiribati"),
    (r"^T31", "Central Kiribati"),
    (r"^T32", "East Kiribati"),
    (r"^T33", "Banaba I."),
    (r"^T5", "Somalia"),
    (r"^T6", "Afghanistan"),
    (r"^T7", "San Marino"),
    (r"^T8", "Palau"),
    (r"^TA", "Turkey"),
    (r"^TB", "Turkey"),
    (r"^TC", "Turkey"),
    (r"^TF", "Iceland"),
    (r"^TG", "Guatemala"),
    (r"^TI9", "Cocos I."),
    (r"^TI", "Costa Rica"),
    (r"^TJ", "Cameroon"),
    (r"^TK", "Corsica"),
    (r"^TL", "Central African Rep."),
    (r"^TN", "Congo (Rep. of the)"),
    (r"^TR", "Gabon"),
    (r"^TT", "Chad"),
    (r"^TU", "Cote d'Ivoire"),
    (r"^TY", "Benin"),
    (r"^TZ", "Mali"),
    (r"^UA2", "Kaliningrad"),
    (r"^UA[0-8]", "European Russia"),
    (r"^UA9", "Asiatic Russia"),
    (r"^UA", "European Russia"),
    (r"^UD", "European Russia"),
    (r"^UE", "European Russia"),
    (r"^UF", "European Russia"),
    (r"^UG", "European Russia"),
    (r"^UH", "European Russia"),
    (r"^UI", "European Russia"),
    (r"^UJ", "Uzbekistan"),
    (r"^UK", "Uzbekistan"),
    (r"^UL", "Kazakhstan"),
    (r"^UM", "Uzbekistan"),
    (r"^UN", "Kazakhstan"),
    (r"^UO", "Kazakhstan"),
    (r"^UP", "Kazakhstan"),
    (r"^UQ", "Kazakhstan"),
    (r"^UR", "Ukraine"),
    (r"^US", "Ukraine"),
    (r"^UT", "Ukraine"),
    (r"^UU", "Ukraine"),
    (r"^UW", "Ukraine"),
    (r"^UX", "Ukraine"),
    (r"^UY", "Ukraine"),
    (r"^UZ", "Ukraine"),
    (r"^V2", "Antigua & Barbuda"),
    (r"^V3", "Belize"),
    (r"^V4", "St. Kitts & Nevis"),
    (r"^V5", "Namibia"),
    (r"^V6", "Micronesia"),
    (r"^V7", "Marshall Is."),
    (r"^V8", "Brunei Darussalam"),
    (r"^VA", "Canada"),
    (r"^VB", "Canada"),
    (r"^VC", "Canada"),
    (r"^VD", "Canada"),
    (r"^VE", "Canada"),
    (r"^VF", "Canada"),
    (r"^VG", "Canada"),
    (r"^VK9C", "Cocos (Keeling) Is."),
    (r"^VK9L", "Lord Howe I."),
    (r"^VK9M", "Mellish Reef"),
    (r"^VK9N", "Norfolk I."),
    (r"^VK9W", "Willis I."),
    (r"^VK9X", "Christmas I."),
    (r"^VK9Y", "Cocos-Keeling"),
    (r"^VK0H", "Heard I."),
    (r"^VK0M", "Macquarie I."),
    (r"^VK0", "Macquarie I."),
    (r"^VK", "Australia"),
    (r"^VO", "Canada (Newfoundland)"),
    (r"^VP2E", "Anguilla"),
    (r"^VP2M", "Montserrat"),
    (r"^VP2V", "British Virgin Is."),
    (r"^VP5", "Turks & Caicos Is."),
    (r"^VP6", "Pitcairn I."),
    (r"^VP8", "Falkland Is."),
    (r"^VP9", "Bermuda"),
    (r"^VQ9", "Chagos Is."),
    (r"^VR", "Hong Kong"),
    (r"^VU", "India"),
    (r"^VY", "Canada"),
    (r"^XA", "Mexico"),
    (r"^XB", "Mexico"),
    (r"^XC", "Mexico"),
    (r"^XD", "Mexico"),
    (r"^XE", "Mexico"),
    (r"^XF", "Mexico"),
    (r"^XG", "Mexico"),
    (r"^XH", "Mexico"),
    (r"^XI", "Mexico"),
    (r"^XT", "Burkina Faso"),
    (r"^XU", "Cambodia"),
    (r"^XW", "Laos"),
    (r"^XX9", "Macao"),
    (r"^XY", "Myanmar"),
    (r"^XZ", "Myanmar"),
    (r"^YA", "Afghanistan"),
    (r"^YB", "Indonesia"),
    (r"^YC", "Indonesia"),
    (r"^YD", "Indonesia"),
    (r"^YE", "Indonesia"),
    (r"^YF", "Indonesia"),
    (r"^YG", "Indonesia"),
    (r"^YH", "Indonesia"),
    (r"^YI", "Iraq"),
    (r"^YJ", "Vanuatu"),
    (r"^YK", "Syria"),
    (r"^YL", "Latvia"),
    (r"^YM", "Turkey"),
    (r"^YN", "Nicaragua"),
    (r"^YO", "Romania"),
    (r"^YP", "Romania"),
    (r"^YQ", "Romania"),
    (r"^YR", "Romania"),
    (r"^YS", "El Salvador"),
    (r"^YT", "Serbia"),
    (r"^YU", "Serbia"),
    (r"^YV0", "Aves I."),
    (r"^YV", "Venezuela"),
    (r"^YY", "Venezuela"),
    (r"^Z2", "Zimbabwe"),
    (r"^Z3", "North Macedonia"),
    (r"^ZA", "Albania"),
    (r"^ZB2", "Gibraltar"),
    (r"^ZC4", "UK Sovereign Bases"),
    (r"^ZD7", "St. Helena"),
    (r"^ZD8", "Ascension I."),
    (r"^ZD9", "Tristan da Cunha"),
    (r"^ZF", "Cayman Is."),
    (r"^ZK2", "Niue"),
    (r"^ZK3", "Tokelau Is."),
    (r"^ZL7", "Chatham Is."),
    (r"^ZL8", "Kermadec Is."),
    (r"^ZL9", "New Zealand Subantarctic"),
    (r"^ZL", "New Zealand"),
    (r"^ZM", "New Zealand"),
    (r"^ZN", "New Zealand"),
    (r"^ZO", "New Zealand"),
    (r"^ZP", "Paraguay"),
    (r"^ZS", "South Africa"),
    (r"^ZT", "South Africa"),
    (r"^ZU", "South Africa"),
    (r"^ZV", "Brazil"),
    (r"^ZX", "Brazil"),
    (r"^ZZ", "Brazil"),
    (r"^4D", "Philippines"),
    (r"^4E", "Philippines"),
    (r"^4F", "Philippines"),
    (r"^4G", "Philippines"),
    (r"^4H", "Philippines"),
    (r"^4I", "Philippines"),
    (r"^6K", "Republic of Korea"),
    (r"^6L", "Republic of Korea"),
    (r"^6M", "Republic of Korea"),
    (r"^6N", "Republic of Korea"),
    (r"^7J", "Japan"),
    (r"^7K", "Japan"),
    (r"^7L", "Japan"),
    (r"^7M", "Japan"),
    (r"^7N", "Japan"),
]

def lookup_dxcc(call_sign: str) -> Optional[str]:
    """通过呼号前缀推断DXCC实体名称"""
    if not call_sign:
        return None

    cs = call_sign.strip().upper()

    # 处理斜杠前缀：b7/ba7abc → 先用 b7 匹配，不行再取 ba7abc
    if "/" in cs:
        parts = cs.split("/")
        # 先尝试用操作地前缀（斜杠前短前缀）匹配
        if parts[0] and len(parts[0]) <= 3:
            for pattern, entity in DXCC_PREFIXES:
                if re.match(pattern, parts[0]):
                    return entity
        # 再用呼号本体匹配
        cs = max(parts, key=len)

    for pattern, entity in DXCC_PREFIXES:
        if re.match(pattern, cs):
            return entity

    return "Unknown"
